version: '2'

services:
    db:
        build: ./mysql
        ports:
            - '8001:3306'
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        restart: always
    php:
        build: ./php
        ports:
            - '6001:80'
            - '7001:443'
            - '9001:9000'
        extra_hosts:
            -  "dockerhost:10.254.254.254"
        environment:
            XDEBUG_CONFIG: "remote_host=10.254.254.254"
        restart: always
        volumes:
            - /var/www/html/logs/demo-error.log:/var/log/apache2/error.log
            - /var/www/html/logs/demo-access.log:/var/log/apache2/access.log
            - /var/www/html/logs/demo-ssl-error.log:/var/log/apache2/ssl_error.log
            - /var/www/html/logs/demo-ssl-access.log:/var/log/apache2/ssl_access.log
            - /var/www/html/demo:/var/www/html
        depends_on:
            - db  
volumes:
    db_data:
